# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeopleTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'JJFloatingActionButton'
  pod 'CocoaMQTT'
  pod 'SideMenu'
  pod 'RealmSwift'
  # Pods for PeopleTracker

  target 'PeopleTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PeopleTrackerUITests' do
    # Pods for testing
  end

end
